// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSNT.Data;

#nullable disable

namespace QLSNT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128064611_4")]
    partial class _4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QLSNT.Models.DanToc", b =>
                {
                    b.Property<int>("MaDanToc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanToc"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanToc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanToc");

                    b.ToTable("DanTocs");
                });

            modelBuilder.Entity("QLSNT.Models.HuyenCu", b =>
                {
                    b.Property<string>("MaHuyenCu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("DanSo")
                        .HasColumnType("bigint");

                    b.Property<double?>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinhCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SLXa")
                        .HasColumnType("int");

                    b.Property<string>("TenHuyenCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhCuMaTinhCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHuyenCu");

                    b.HasIndex("TinhCuMaTinhCu");

                    b.ToTable("HuyenCus");
                });

            modelBuilder.Entity("QLSNT.Models.LichSuDiaChi", b =>
                {
                    b.Property<string>("MaLichSuCuTru")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThayDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoThayDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXaCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDanMaCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XaCuMaXaCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaLichSuCuTru");

                    b.HasIndex("NguoiDanMaCCCD");

                    b.HasIndex("XaCuMaXaCu");

                    b.ToTable("LichSuDiaChis");
                });

            modelBuilder.Entity("QLSNT.Models.LichSuSapNhap", b =>
                {
                    b.Property<string>("MaLSSN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoNghiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuKienHanhChinhSoNghiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaLSSN");

                    b.HasIndex("SuKienHanhChinhSoNghiDinh");

                    b.ToTable("LichSuSapNhaps");
                });

            modelBuilder.Entity("QLSNT.Models.LssnTinh", b =>
                {
                    b.Property<string>("MaLSSN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LichSuSapNhapMaLSSN")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinhCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhCuMaTinhCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhMoiMaTinhMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaLSSN");

                    b.HasIndex("LichSuSapNhapMaLSSN");

                    b.HasIndex("TinhCuMaTinhCu");

                    b.HasIndex("TinhMoiMaTinhMoi");

                    b.ToTable("LssnTinhs");
                });

            modelBuilder.Entity("QLSNT.Models.LssnXa", b =>
                {
                    b.Property<string>("MaLSSN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LichSuSapNhapMaLSSN")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaXaCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXaMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XaCuMaXaCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("XaMoiMaXaMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaLSSN");

                    b.HasIndex("LichSuSapNhapMaLSSN");

                    b.HasIndex("XaCuMaXaCu");

                    b.HasIndex("XaMoiMaXaMoi");

                    b.ToTable("LssnXas");
                });

            modelBuilder.Entity("QLSNT.Models.NguoiDan", b =>
                {
                    b.Property<string>("MaCCCD")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("DanTocMaDanToc")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenKhongDau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQHCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTDVH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHeChuHoMaQHCH")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhTrangHonNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiaoMaTonGiao")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrangThaiCongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoVanHoaMaTDVH")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaCCCD");

                    b.HasIndex("DanTocMaDanToc");

                    b.HasIndex("QuanHeChuHoMaQHCH");

                    b.HasIndex("TonGiaoMaTonGiao");

                    b.HasIndex("TrinhDoVanHoaMaTDVH");

                    b.ToTable("NguoiDans");
                });

            modelBuilder.Entity("QLSNT.Models.QuanHeChuHo", b =>
                {
                    b.Property<string>("MaQHCH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQHCH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQHCH");

                    b.ToTable("QuanHeChuHos");
                });

            modelBuilder.Entity("QLSNT.Models.SuKienHanhChinh", b =>
                {
                    b.Property<string>("SoNghiDinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CanCuPhapLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoQuanBanHanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBanHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoNghiDinh");

                    b.ToTable("SuKienHanhChinhs");
                });

            modelBuilder.Entity("QLSNT.Models.TamTru", b =>
                {
                    b.Property<string>("MaXaMoi")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCCCD")
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungDeNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiHan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaXaMoi", "MaCCCD");

                    b.HasIndex("MaCCCD");

                    b.ToTable("TamTrus");
                });

            modelBuilder.Entity("QLSNT.Models.ThuongTru", b =>
                {
                    b.Property<string>("MaXaMoi")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCCCD")
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("MaXaMoi", "MaCCCD");

                    b.HasIndex("MaCCCD");

                    b.ToTable("ThuongTrus");
                });

            modelBuilder.Entity("QLSNT.Models.TinhCu", b =>
                {
                    b.Property<string>("MaTinhCu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("DanSo")
                        .HasColumnType("bigint");

                    b.Property<double?>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SLHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("SLXa")
                        .HasColumnType("int");

                    b.Property<string>("TenTinhCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VungDiaLy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinhCu");

                    b.ToTable("TinhCus");
                });

            modelBuilder.Entity("QLSNT.Models.TinhMoi", b =>
                {
                    b.Property<string>("MaTinhMoi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("DanSo")
                        .HasColumnType("bigint");

                    b.Property<double?>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SLHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("SLXa")
                        .HasColumnType("int");

                    b.Property<string>("TenTinhMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VungDiaLy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinhMoi");

                    b.ToTable("TinhMois");
                });

            modelBuilder.Entity("QLSNT.Models.TonGiao", b =>
                {
                    b.Property<string>("MaTonGiao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTonGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTonGiao");

                    b.ToTable("TonGiaos");
                });

            modelBuilder.Entity("QLSNT.Models.TrinhDoVanHoa", b =>
                {
                    b.Property<string>("MaTDVH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTDVH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTDVH");

                    b.ToTable("TrinhDoVanHoas");
                });

            modelBuilder.Entity("QLSNT.Models.XaCu", b =>
                {
                    b.Property<string>("MaXaCu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("DanSo")
                        .HasColumnType("bigint");

                    b.Property<double?>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuyenCuMaHuyenCu")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LoaiXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyenCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SLAp")
                        .HasColumnType("int");

                    b.Property<string>("TenXaCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaXaCu");

                    b.HasIndex("HuyenCuMaHuyenCu");

                    b.ToTable("XaCus");
                });

            modelBuilder.Entity("QLSNT.Models.XaMoi", b =>
                {
                    b.Property<string>("MaXaMoi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("DanSo")
                        .HasColumnType("bigint");

                    b.Property<double?>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SLAp")
                        .HasColumnType("int");

                    b.Property<string>("TenXaMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaXaMoi");

                    b.HasIndex("MaTinh");

                    b.ToTable("XaMois");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLSNT.Models.HuyenCu", b =>
                {
                    b.HasOne("QLSNT.Models.TinhCu", "TinhCu")
                        .WithMany("HuyenCus")
                        .HasForeignKey("TinhCuMaTinhCu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhCu");
                });

            modelBuilder.Entity("QLSNT.Models.LichSuDiaChi", b =>
                {
                    b.HasOne("QLSNT.Models.NguoiDan", "NguoiDan")
                        .WithMany("LichSuDiaChis")
                        .HasForeignKey("NguoiDanMaCCCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSNT.Models.XaCu", "XaCu")
                        .WithMany()
                        .HasForeignKey("XaCuMaXaCu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDan");

                    b.Navigation("XaCu");
                });

            modelBuilder.Entity("QLSNT.Models.LichSuSapNhap", b =>
                {
                    b.HasOne("QLSNT.Models.SuKienHanhChinh", "SuKienHanhChinh")
                        .WithMany("LichSuSapNhaps")
                        .HasForeignKey("SuKienHanhChinhSoNghiDinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuKienHanhChinh");
                });

            modelBuilder.Entity("QLSNT.Models.LssnTinh", b =>
                {
                    b.HasOne("QLSNT.Models.LichSuSapNhap", "LichSuSapNhap")
                        .WithMany("LssnTinhs")
                        .HasForeignKey("LichSuSapNhapMaLSSN");

                    b.HasOne("QLSNT.Models.TinhCu", "TinhCu")
                        .WithMany()
                        .HasForeignKey("TinhCuMaTinhCu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSNT.Models.TinhMoi", "TinhMoi")
                        .WithMany("LssnTinhs")
                        .HasForeignKey("TinhMoiMaTinhMoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichSuSapNhap");

                    b.Navigation("TinhCu");

                    b.Navigation("TinhMoi");
                });

            modelBuilder.Entity("QLSNT.Models.LssnXa", b =>
                {
                    b.HasOne("QLSNT.Models.LichSuSapNhap", "LichSuSapNhap")
                        .WithMany("LssnXas")
                        .HasForeignKey("LichSuSapNhapMaLSSN");

                    b.HasOne("QLSNT.Models.XaCu", "XaCu")
                        .WithMany()
                        .HasForeignKey("XaCuMaXaCu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSNT.Models.XaMoi", "XaMoi")
                        .WithMany("LssnXas")
                        .HasForeignKey("XaMoiMaXaMoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichSuSapNhap");

                    b.Navigation("XaCu");

                    b.Navigation("XaMoi");
                });

            modelBuilder.Entity("QLSNT.Models.NguoiDan", b =>
                {
                    b.HasOne("QLSNT.Models.DanToc", "DanToc")
                        .WithMany("NguoiDans")
                        .HasForeignKey("DanTocMaDanToc");

                    b.HasOne("QLSNT.Models.QuanHeChuHo", "QuanHeChuHo")
                        .WithMany("NguoiDans")
                        .HasForeignKey("QuanHeChuHoMaQHCH");

                    b.HasOne("QLSNT.Models.TonGiao", "TonGiao")
                        .WithMany("NguoiDans")
                        .HasForeignKey("TonGiaoMaTonGiao");

                    b.HasOne("QLSNT.Models.TrinhDoVanHoa", "TrinhDoVanHoa")
                        .WithMany("NguoiDans")
                        .HasForeignKey("TrinhDoVanHoaMaTDVH");

                    b.Navigation("DanToc");

                    b.Navigation("QuanHeChuHo");

                    b.Navigation("TonGiao");

                    b.Navigation("TrinhDoVanHoa");
                });

            modelBuilder.Entity("QLSNT.Models.TamTru", b =>
                {
                    b.HasOne("QLSNT.Models.NguoiDan", "NguoiDan")
                        .WithMany("TamTrus")
                        .HasForeignKey("MaCCCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSNT.Models.XaMoi", "XaMoi")
                        .WithMany("TamTrus")
                        .HasForeignKey("MaXaMoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDan");

                    b.Navigation("XaMoi");
                });

            modelBuilder.Entity("QLSNT.Models.ThuongTru", b =>
                {
                    b.HasOne("QLSNT.Models.NguoiDan", "NguoiDan")
                        .WithMany("ThuongTrus")
                        .HasForeignKey("MaCCCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSNT.Models.XaMoi", "XaMoi")
                        .WithMany("ThuongTrus")
                        .HasForeignKey("MaXaMoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDan");

                    b.Navigation("XaMoi");
                });

            modelBuilder.Entity("QLSNT.Models.XaCu", b =>
                {
                    b.HasOne("QLSNT.Models.HuyenCu", "HuyenCu")
                        .WithMany("XaCus")
                        .HasForeignKey("HuyenCuMaHuyenCu");

                    b.Navigation("HuyenCu");
                });

            modelBuilder.Entity("QLSNT.Models.XaMoi", b =>
                {
                    b.HasOne("QLSNT.Models.TinhMoi", "TinhMoi")
                        .WithMany("XaMois")
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhMoi");
                });

            modelBuilder.Entity("QLSNT.Models.DanToc", b =>
                {
                    b.Navigation("NguoiDans");
                });

            modelBuilder.Entity("QLSNT.Models.HuyenCu", b =>
                {
                    b.Navigation("XaCus");
                });

            modelBuilder.Entity("QLSNT.Models.LichSuSapNhap", b =>
                {
                    b.Navigation("LssnTinhs");

                    b.Navigation("LssnXas");
                });

            modelBuilder.Entity("QLSNT.Models.NguoiDan", b =>
                {
                    b.Navigation("LichSuDiaChis");

                    b.Navigation("TamTrus");

                    b.Navigation("ThuongTrus");
                });

            modelBuilder.Entity("QLSNT.Models.QuanHeChuHo", b =>
                {
                    b.Navigation("NguoiDans");
                });

            modelBuilder.Entity("QLSNT.Models.SuKienHanhChinh", b =>
                {
                    b.Navigation("LichSuSapNhaps");
                });

            modelBuilder.Entity("QLSNT.Models.TinhCu", b =>
                {
                    b.Navigation("HuyenCus");
                });

            modelBuilder.Entity("QLSNT.Models.TinhMoi", b =>
                {
                    b.Navigation("LssnTinhs");

                    b.Navigation("XaMois");
                });

            modelBuilder.Entity("QLSNT.Models.TonGiao", b =>
                {
                    b.Navigation("NguoiDans");
                });

            modelBuilder.Entity("QLSNT.Models.TrinhDoVanHoa", b =>
                {
                    b.Navigation("NguoiDans");
                });

            modelBuilder.Entity("QLSNT.Models.XaMoi", b =>
                {
                    b.Navigation("LssnXas");

                    b.Navigation("TamTrus");

                    b.Navigation("ThuongTrus");
                });
#pragma warning restore 612, 618
        }
    }
}
